name: Feature request
description: Suggest an idea for Gal Launcher.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      placeholder: I want to...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to happen?
      placeholder: It would be nice if...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: I also thought about...
